on:
  push:
    branches:
      - main
      - qa
      - lab9
  pull_request:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack and Install PNPM
        run: |
          corepack enable
          corepack prepare pnpm@latest-10 --activate

      - name: Cache PNPM Store and Node Modules
        uses: actions/cache@v3
        with:
          path: |
            .pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

              - name: Install Dependencies
        run: |
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Build
        run: pnpm build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  deploy-qa:
    name: Deploy to Azure Static Web App (QA)
    needs: build
    if: github.ref == 'refs/heads/qa'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
  
      - name: Deploy to Azure Static Web Apps (QA)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_QA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/dist" # where your built frontend lives
          environment: "QA"
            
          
