on:
  push:
    branches:
      - main
      - lab9
  pull_request:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js and enable corepack
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'pnpm'

      - name: Enable and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest-10 --activate
          pnpm config set store-dir .pnpm-store

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: QA

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Deploy to QA
        run: pnpx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-qa --env=preview
  
        
  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: PROD

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Deploy to Production
        run: pnpx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-prod --env=production
